openapi: 3.0.0
info:
  version: 0.1.0
  title: Team 6 Express API with Swagger
  description: This is a API application made with Express and documented with Swagger
  license:
    name: MIT
servers:
  - url: http://localhost:8000/api
    description: Development Server URL
  # - url: http://localhost:3000/api
  #   description: Production Server URL
tags:
  - name: Auth
  # - name: Post
paths:
  $ref: "./paths/v1/index.yaml"
components:
  schemas:
    User:
      type: object
      required:
        - id
        - email
        - password
      properties:
        id:
          type: number
          example: 1
        nickname:
          type: string
          description: 유저 닉네임
          example: 팀6
        username:
          type: string
          description: 유저 이름
          example: 홍길동
        email:
          type: string
          description: 유저 이메일 (Unique)
          example: admin@gmail.com
        password:
          type: string
          description: 유저 비밀번호
          example: qwer1234
        oauthId:
          type: string
          description: 소설 로그인 Oauth id 값 (nullable)
        provider:
          type: string
          description: 소셜 로그인 제공자 (default local)
          example: local
    Post:
      type: object
      required:
        - id
      properties:
        id:
          type: number
          example: 1
        title:
          type: string
          description: 글 제목
          example: Team 6 블로그에 오신 것을 환영합니다.
        content:
          type: string
          description: 글 내용
          example: Team 6 Post.
        createdAt:
          type: string
          description: 글 생성일자
        hits:
          type: number
          description: 글 좋아요 수
          example: 100
        views:
          type: number
          description: 글 뷰어 수
          example: 100
    Comment:
      type: object
      required:
        - id
      properties:
        id:
          type: number
          example: 1
        content:
          type: string
          description: 댓글 내용
          example: Team 6 Comment.
        createdAt:
          type: string
          description: 댓글 생성일자
        hits:
          type: number
          description: 댓글 좋아요 수
          example: 100
    HashTag:
      type: object
      required:
        - id
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          description: 해시태그 이름
          example: python
    Error:
      type: object
      properties:
        status:
          type: number
        message:
          type: string
        data:
          type: object
  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            status: 400
            message: 잘못된 요청
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            status: 500
            message: 서버 내부 오류
    DBError:
      description: 데이터베이스 에러
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            status: 600
            message: 데이터베이스 에러
