openapi: 3.0.0
info:
  version: 0.1.0
  title: Team 6 Express API with Swagger
  description: This is a API application made with Express and documented with Swagger
  license:
    name: MIT
servers:
  - url: http://localhost:8000/api
    description: Development Server URL
  # - url: http://localhost:3000/api
  #   description: Production Server URL
tags:
  - name: Auth
  # - name: Post
paths:
  $ref: "./paths/v1/index.yaml"
security:
  - bearerAuth: [] # use the same name as above
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
        - id
        - email
        - password
      properties:
        nickname:
          type: string
          description: 유저 닉네임
          example: Ryan
        username:
          type: string
          description: 유저 이름
          example: 홍길동
        email:
          type: string
          description: 유저 이메일 (Unique)
          example: admin@gmail.com
        password:
          type: string
          description: 유저 비밀번호
          example: qwer1234
    Post:
      type: object
      required:
        - id
      properties:
        title:
          type: string
          description: 글 제목
          example: Team 6 블로그에 오신 것을 환영합니다.
        content:
          type: string
          description: 글 내용
          example: Team 6 Post.
    Comment:
      type: object
      required:
        - id
      properties:
        id:
          type: number
          example: 1
        content:
          type: string
          description: 댓글 내용
          example: Team 6 Comment.
        createdAt:
          type: string
          description: 댓글 생성일자
          example: "2021-05-18T02:31:16.207Z"
        likes:
          type: number
          description: 댓글 좋아요 수
          example: 100
    HashTag:
      type: object
      required:
        - id
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          description: 해시태그 이름
          example: python
    Error:
      type: object
      properties:
        status:
          type: number
        message:
          type: string
        success:
          type: boolean
        data:
          type: object
  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            status: 400
            message: 잘못된 요청
            success: false
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            status: 500
            message: 서버 내부 오류
            success: false
    DBError:
      description: 데이터베이스 에러
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            status: 600
            message: 데이터베이스 에러
            success: false
